# This file was generated by Project Manager.
{ allow-import-from-derivation = false; auto-retry = true; build-logs = true; cachix = { name = "sellout"; public-key = "sellout.cachix.org-1:v37cTpWBEycnYxSPAgSQ57Wiqd3wjljni2aC0Xry1DE="; }; deploy = { }; doNotBuild = [ "devShells.x86_64-linux.lax-checks" ]; enable = true; fail-fast = false; impure = false; test = { }; }
